"""initial schema

Revision ID: 71cb28cd62c7
Revises: 
Create Date: 2026-09-18 18:36:20.934823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71cb28cd62c7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('companies',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.String(length=120), nullable=True),
    sa.Column('headquarters_location', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('size_band', sa.String(length=40), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=True)
    op.create_index(op.f('ix_companies_slug'), 'companies', ['slug'], unique=True)
    op.create_table('job_sources',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.String(length=60), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('respects_robots_txt', sa.Boolean(), nullable=False),
    sa.Column('rate_limit_per_minute', sa.Integer(), nullable=False),
    sa.Column('last_polled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('skills',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('category', sa.Enum('PROGRAMMING_LANGUAGE', 'FRAMEWORK', 'AI_ML', 'CLOUD_DEVOPS', 'TOOL', 'OTHER', name='skillcategory'), nullable=False),
    sa.Column('aliases', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skills_name'), 'skills', ['name'], unique=True)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('jobs',
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('original_description', sa.Text(), nullable=False),
    sa.Column('description_language', sa.String(length=10), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=False),
    sa.Column('source_job_id', sa.String(length=255), nullable=True),
    sa.Column('canonical_url', sa.String(length=1000), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('salary_min', sa.Integer(), nullable=True),
    sa.Column('salary_max', sa.Integer(), nullable=True),
    sa.Column('salary_currency', sa.String(length=10), nullable=True),
    sa.Column('employment_type', sa.Enum('FULL_TIME', 'INTERNSHIP', 'CONTRACT', 'NEW_GRADUATE', name='employmenttype'), nullable=False),
    sa.Column('work_mode', sa.Enum('ONSITE', 'HYBRID', 'REMOTE', 'UNKNOWN', name='workmode'), nullable=False),
    sa.Column('application_deadline', sa.String(length=20), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'CLOSED', 'STALE', 'UNKNOWN', name='jobstatus'), nullable=False),
    sa.Column('is_demo_data', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['job_sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_content_hash'), 'jobs', ['content_hash'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_table('notification_preferences',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('frequency', sa.Enum('INSTANT', 'DAILY_DIGEST', 'WEEKLY_DIGEST', 'OFF', name='notificationfrequency'), nullable=False),
    sa.Column('email_enabled', sa.Boolean(), nullable=False),
    sa.Column('push_enabled', sa.Boolean(), nullable=False),
    sa.Column('min_match_threshold', sa.Float(), nullable=False),
    sa.Column('max_notifications_per_day', sa.Integer(), nullable=False),
    sa.Column('notify_new_graduate', sa.Boolean(), nullable=False),
    sa.Column('notify_visa_related', sa.Boolean(), nullable=False),
    sa.Column('notify_high_match_only', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('profiles',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('country', sa.String(length=120), nullable=True),
    sa.Column('current_location', sa.String(length=120), nullable=True),
    sa.Column('preferred_japan_locations', sa.JSON(), nullable=False),
    sa.Column('years_of_experience', sa.Float(), nullable=False),
    sa.Column('is_new_graduate', sa.Boolean(), nullable=False),
    sa.Column('jlpt_level', sa.Enum('NONE', 'N5', 'N4', 'N3', 'N2', 'N1', name='jlptlevel'), nullable=False),
    sa.Column('japanese_speaking_level', sa.Enum('NONE', 'BASIC', 'CONVERSATIONAL', 'BUSINESS', 'FLUENT', 'NATIVE', name='japaneselevel'), nullable=False),
    sa.Column('japanese_reading_level', sa.Enum('NONE', 'BASIC', 'CONVERSATIONAL', 'BUSINESS', 'FLUENT', 'NATIVE', name='japaneselevel'), nullable=False),
    sa.Column('japanese_writing_level', sa.Enum('NONE', 'BASIC', 'CONVERSATIONAL', 'BUSINESS', 'FLUENT', 'NATIVE', name='japaneselevel'), nullable=False),
    sa.Column('business_japanese_ability', sa.Enum('NONE', 'BASIC', 'CONVERSATIONAL', 'BUSINESS', 'FLUENT', 'NATIVE', name='japaneselevel'), nullable=False),
    sa.Column('english_level', sa.Enum('NONE', 'BASIC', 'CONVERSATIONAL', 'BUSINESS', 'FLUENT', 'NATIVE', name='japaneselevel'), nullable=False),
    sa.Column('desired_roles', sa.JSON(), nullable=False),
    sa.Column('work_mode_preference', sa.Enum('ONSITE', 'HYBRID', 'REMOTE', 'UNKNOWN', name='workmode'), nullable=False),
    sa.Column('employment_type_preference', sa.Enum('FULL_TIME', 'INTERNSHIP', 'CONTRACT', 'NEW_GRADUATE', name='employmenttype'), nullable=False),
    sa.Column('salary_expectation_min', sa.Integer(), nullable=True),
    sa.Column('salary_expectation_max', sa.Integer(), nullable=True),
    sa.Column('company_size_preference', sa.String(length=40), nullable=True),
    sa.Column('industry_preference', sa.JSON(), nullable=False),
    sa.Column('visa_sponsorship_required', sa.Boolean(), nullable=False),
    sa.Column('resume_file_path', sa.String(length=500), nullable=True),
    sa.Column('resume_original_filename', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('applications',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('SAVED', 'APPLIED', 'INTERVIEW', 'OFFER', 'REJECTED', 'ARCHIVED', name='applicationstatus'), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'job_id', name='uq_application_user_job')
    )
    op.create_index(op.f('ix_applications_job_id'), 'applications', ['job_id'], unique=False)
    op.create_index(op.f('ix_applications_user_id'), 'applications', ['user_id'], unique=False)
    op.create_table('certifications',
    sa.Column('profile_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('issuer', sa.String(length=255), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('education',
    sa.Column('profile_id', sa.String(), nullable=False),
    sa.Column('degree', sa.String(length=120), nullable=False),
    sa.Column('university', sa.String(length=255), nullable=False),
    sa.Column('field_of_study', sa.String(length=255), nullable=True),
    sa.Column('graduation_year', sa.Integer(), nullable=True),
    sa.Column('is_current_student', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('experience',
    sa.Column('profile_id', sa.String(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=False),
    sa.Column('is_internship', sa.Boolean(), nullable=False),
    sa.Column('start_date', sa.String(length=20), nullable=True),
    sa.Column('end_date', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_embeddings',
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('model_name', sa.String(length=120), nullable=False),
    sa.Column('vector', sa.JSON(), nullable=False),
    sa.Column('source_text_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    op.create_table('job_requirements',
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('required_skills', sa.JSON(), nullable=False),
    sa.Column('preferred_skills', sa.JSON(), nullable=False),
    sa.Column('education_requirement', sa.String(length=255), nullable=True),
    sa.Column('minimum_experience_years', sa.Float(), nullable=True),
    sa.Column('jlpt_requirement', sa.Enum('NONE', 'N5', 'N4', 'N3', 'N2', 'N1', name='jlptlevel'), nullable=True),
    sa.Column('japanese_requirement_raw', sa.Text(), nullable=True),
    sa.Column('japanese_requirement_level', sa.Enum('NONE', 'BASIC', 'CONVERSATIONAL', 'BUSINESS', 'FLUENT', 'NATIVE', name='japaneselevel'), nullable=True),
    sa.Column('english_requirement_raw', sa.Text(), nullable=True),
    sa.Column('english_requirement_level', sa.Enum('NONE', 'BASIC', 'CONVERSATIONAL', 'BUSINESS', 'FLUENT', 'NATIVE', name='japaneselevel'), nullable=True),
    sa.Column('visa_sponsorship', sa.Enum('YES', 'NO', 'NOT_STATED', name='visasponsorship'), nullable=False),
    sa.Column('new_graduate_allowed', sa.Boolean(), nullable=True),
    sa.Column('internship_eligible', sa.Boolean(), nullable=True),
    sa.Column('extraction_source', sa.String(length=20), nullable=False),
    sa.Column('extraction_confidence', sa.Float(), nullable=False),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_extraction_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    op.create_table('job_verification',
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status_found', sa.Enum('ACTIVE', 'CLOSED', 'STALE', 'UNKNOWN', name='jobstatus'), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matches',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('deterministic_pass', sa.Boolean(), nullable=False),
    sa.Column('semantic_score', sa.Float(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('match_strength', sa.Enum('STRONG', 'PARTIAL', 'SIGNIFICANT_GAPS', name='matchstrength'), nullable=False),
    sa.Column('requirement_breakdown', sa.JSON(), nullable=False),
    sa.Column('ai_explanation', sa.Text(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'job_id', name='uq_match_user_job')
    )
    op.create_index(op.f('ix_matches_job_id'), 'matches', ['job_id'], unique=False)
    op.create_index(op.f('ix_matches_user_id'), 'matches', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=True),
    sa.Column('type', sa.Enum('NEW_MATCH', 'JOB_BECAME_MATCH', 'JOB_STATUS_CHANGED', 'DIGEST', 'SYSTEM', name='notificationtype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('reason_summary', sa.Text(), nullable=True),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('projects',
    sa.Column('profile_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('technologies', sa.JSON(), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=True),
    sa.Column('github_url', sa.String(length=500), nullable=True),
    sa.Column('project_url', sa.String(length=500), nullable=True),
    sa.Column('duration', sa.String(length=120), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saved_jobs',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('saved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'job_id', name='uq_saved_user_job')
    )
    op.create_index(op.f('ix_saved_jobs_job_id'), 'saved_jobs', ['job_id'], unique=False)
    op.create_index(op.f('ix_saved_jobs_user_id'), 'saved_jobs', ['user_id'], unique=False)
    op.create_table('user_skills',
    sa.Column('profile_id', sa.String(), nullable=False),
    sa.Column('skill_id', sa.String(), nullable=False),
    sa.Column('proficiency', sa.String(length=40), nullable=True),
    sa.Column('years_experience', sa.Float(), nullable=True),
    sa.Column('is_ai_ml', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_skills')
    op.drop_index(op.f('ix_saved_jobs_user_id'), table_name='saved_jobs')
    op.drop_index(op.f('ix_saved_jobs_job_id'), table_name='saved_jobs')
    op.drop_table('saved_jobs')
    op.drop_table('projects')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_matches_user_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_job_id'), table_name='matches')
    op.drop_table('matches')
    op.drop_table('job_verification')
    op.drop_table('job_requirements')
    op.drop_table('job_embeddings')
    op.drop_table('experience')
    op.drop_table('education')
    op.drop_table('certifications')
    op.drop_index(op.f('ix_applications_user_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_job_id'), table_name='applications')
    op.drop_table('applications')
    op.drop_table('profiles')
    op.drop_table('notification_preferences')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_content_hash'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_skills_name'), table_name='skills')
    op.drop_table('skills')
    op.drop_table('job_sources')
    op.drop_index(op.f('ix_companies_slug'), table_name='companies')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_table('companies')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
